# Generated by Django 4.1.7 on 2023-05-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_name_patient_username_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='patient',
        ),
        migrations.AddField(
            model_name='disease',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.patient'),
        ),
    ]
