# Generated by Django 4.1.7 on 2023-06-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_patient_first_name_alter_patient_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_doctor',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(max_length=200),
        ),
    ]
